# Generated by Django 3.1.1 on 2020-09-26 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Trader'), (3, 'Analyst')], null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bot_user_id', models.CharField(blank=True, max_length=127, null=True, unique=True)),
                ('bot_first_name', models.CharField(blank=True, max_length=127, null=True)),
                ('bot_last_name', models.CharField(blank=True, max_length=127, null=True)),
                ('bot_username', models.CharField(blank=True, max_length=127, null=True)),
                ('bot_expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_future_expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
